table Organizations

	column organization_id
		dataType: string
		summarizeBy: none
		sourceColumn: organization_id

	column organization
		dataType: string
		summarizeBy: none
		sourceColumn: organization

	column organization_type
		dataType: string
		summarizeBy: none
		sourceColumn: organization_type

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city

	partition Organizations = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-b66dca1a-d331.cloud.databricks.com", "/sql/1.0/warehouses/87abf2d5aeeae691", null),
				    Catalog = Source{[Name = "fhir", Kind = "Database"]}[Data],
				    Schema = Catalog{[Name = "dev_osamagul08_fhir_etl", Kind = "Schema"]}[Data],
				    Data = Schema{[Name = "gold_dim_organization", Kind = "View"]}[Data],
				    Kept = Table.SelectColumns(Data, {"organization_id", "organization", "organization_type", "city"}),
				    Typed = Table.TransformColumnTypes(Kept, {{"organization_id", type text}, {"organization", type text}, {"organization_type", type text}, {"city", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table
